version: '3.4'

services:
#PostgreSQL
  postgresql:
    container_name: postgres_container
    image: postgres:14
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: postgres_db
        PGDATA: /var/lib/postgresql/data
        POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
        - "5432:5432"
    volumes: 
        - ./PostgreSQL/src:/var/lib/postgresql/data/

#PGAdmin4
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    depends_on:
      - postgresql
    environment: 
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: secret
    ports:
        - 5050:80
    volumes: 
        - pgadmin:/var/lib/pgadmin

#Web Client
  www:
    depends_on:
      - postgresql
    container_name: "web"
    build:
      context: .
      dockerfile: ./Web/Dockerfile  
    ports:
      - 3080:80
    tty: true
    volumes:
      - ./Web/src/:/var/www/html/
      - /var/www/html/PHP/DISPLAY/templates_c
      - /var/www/html/templates_c

#NodeJS server
  node:
    container_name: "nodejs"
    build:
      context: .
      dockerfile: ./Node/Dockerfile
    tty: true
    ports:
      - 8080:8080 
    volumes:
      - ./Node/src:/serveur/src
    #devices:
      #- "/dev/ttyUSB0:/dev/ttyUSB0"

volumes:
  pgadmin: